name: s3gui
description: S3 GUI for desktop and mobile.

publish_to: 'none'

version: 0.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  minio: ^3.5.8
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1
  timeago: ^3.7.0
  file_picker: ^8.0.0
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.2
  desktop_drop: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Balsamiq
      fonts:
        - asset: assets/fonts/Balsamiq-Sans.ttf
