name: Publish

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  android:
    name: "Publish Android"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: android_bundle
          path: build/app/outputs/bundle/release/app.aab

  web:
    runs-on: "ubuntu-latest"
    name: "Publish Web"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web/

  linux:
    name: "Publish Linux"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux_x64
          path: build/linux/x64/release/bundle/

  windows:
    runs-on: windows-latest
    name: "Publish Windows"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows_64
          path: build/windows/runner/Release/
